<?xml version="1.0" encoding="utf-8"?><testsuite errors="0" failures="0" name="pytest" skipped="0" tests="3" time="0.791"><testcase classname="testCase.zzj.test_OrderInquiry" file="testCase\zzj\test_OrderInquiry.py" line="33" name="test_01_querySecOrder_正确报文获取最新的第二笔订单" time="0.083"></testcase><testcase classname="testCase.zzj.test_OrderInquiry" file="testCase\zzj\test_OrderInquiry.py" line="63" name="test_02_querySecOrder_获取内容失败" time="0.064"></testcase><testcase classname="testCase.zzj.test_OrderInquiry" file="testCase\zzj\test_OrderInquiry.py" line="93" name="test_03_querySecOrder_报文内容中为空为空字符串时接口给出正确的错误提示" time="0.070"><system-out>{&quot;code&quot;:9999,&quot;result&quot;:null,&quot;message&quot;:&quot;系统异常&quot;,&quot;success&quot;:false}
9999
</system-out></testcase></testsuite>